server:
  port: 18300
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: api
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    url: jdbc:postgresql://168.107.51.69:5432/raceon
    username: raceon
    password: raceon12#
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


jwt:
  secret: cmFjZW9uLWp3dC1zZWNyZXQta2V5LWZvci1zZWN1cmUtYXV0aC10b2tlbi0yMDI1
  expiration: 86400000

upload:
  base-path: ./upload
